### ISSUE TITLE
Hotspot issues

### ISSUE THREAD

**Issue by ErikDeridder** [nunocodex/PixelExperience-Builds#28]
Installed latest build version 20191013-1600-beta

When i used a simple password it doesn't work. My password was "erikerik" and devices could not connect. When i used a more complex one it did work

But unable to get 5Ghz working. When setting to 5Ghz, wifi hotspot stay off

**Comment by nunocodex** [comment]
Announcement Regarding 5GHz Wi-Fi Hotspots (Band 1)

Hello Mi Fans,

5GHz Wi-Fi hotspots (band 1) will no longer be supported on our products in the following countries and regions due to the EU restrictions on the indoor use of 5Ghz bands 1 and 2.


1. 27 member states of the European Union:
Austria, Belgium, Bulgaria, Croatia, Cyprus, Czechia, Denmark, Estonia, Finland, France, Germany, Greece, Hungary, Ireland, Italy, Latvia, Lithuania, Luxembourg, Malta, Netherlands, Poland, Portugal, Romania, Slovakia, Slovenia, Spain, Sweden.

2. Countries and regions that recognize the CE marking:
Egypt, Hong Kong SAR (China), Singapore, Turkey, Ukraine.


The support of this functionality (if any) will be removed from the currently retailed devices in the coming software updates.


Thanks for your understanding.
Source: https://en.miui.com/thread-4944909-1-1.html
